ALTER TABLE manpower_cost_report
ADD COLUMN IF NOT EXISTS training_hrs NUMERIC(6,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS training_rate NUMERIC(10,2) NOT NULL DEFAULT 8.00,
ADD COLUMN IF NOT EXISTS star_coach_hrs NUMERIC(6,2) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS star_coach_rate NUMERIC(10,2) NOT NULL DEFAULT 50.00;
