// ─────────────────────────────────────────────────────────────
// Audit log — primary-key column for every model in prisma/schema.prisma.
//
// GENERATED by scripts/gen-audit-primary-keys.ts — re-run that after adding
// or renaming a model. Prisma 7's runtime DMMF is trimmed (fields carry no
// `isId`), so the audit extension cannot discover these at run time.
//
// A model missing from this map still audits correctly: entityIdOf() falls
// back to the first id-shaped key on the row, which is the primary key for
// every model in this schema (each declares its `@id` field first).
// ─────────────────────────────────────────────────────────────

export const PRIMARY_KEYS: Record<string, string> = {
  achievement: "achievement_id",
  analytics_metric: "id",
  announcement: "id",
  annual_leave_record: "id",
  attendance: "attendance_id",
  attendance_all: "id",
  attendance_justification: "id",
  attendance_log: "log_id",
  bank_details: "bank_id",
  branch: "branch_id",
  branch_operating_day: "branch_operating_day_id",
  branch_position: "branch_position_id",
  branch_position_day: "branch_position_day_id",
  claim: "claim_id",
  department: "department_id",
  department_chat_message: "id",
  devices: "device_id",
  documents: "documents_id",
  domestic_inquiry: "domestic_inquiry_id",
  emergency_contact: "contract_id",
  employee_rate_history: "rate_history_id",
  employment: "employment_id",
  employment_schedule_version: "id",
  exit_asset_recovery_item: "id",
  exit_asset_recovery_state: "id",
  exit_financial_settlement: "id",
  exit_interview_note: "exit_interview_note_id",
  exit_knowledge_transfer_item: "id",
  exit_knowledge_transfer_state: "id",
  exit_system_revocation_item: "id",
  exit_system_revocation_state: "id",
  guardian_info: "guardian_info_id",
  impact_log: "id",
  induction_profile: "id",
  induction_request: "id",
  induction_step: "id",
  induction_substep_template: "id",
  interview_assessment: "interview_assessment_id",
  leave_request: "leave_id",
  leave_types: "leave_type_id",
  manpower_attendance_day_lock: "day_lock_id",
  manpower_cost_report: "manpower_cost_report_id",
  manpower_schedule: "mp_schedule_id",
  manpower_schedule_attendance: "attendance_id",
  manpower_schedule_note: "note_id",
  mc_record: "id",
  medical_check: "medical_check_id",
  nda: "nda_id",
  non_compete: "non_compete_id",
  od_tickets: "id",
  offboarding_audit_log: "id",
  offboarding_case: "id",
  offboarding_checklist_item: "id",
  onboarding_candidate: "id",
  password_reset_token: "token_id",
  payment_info: "payment_info_id",
  payroll: "payroll_id",
  payslip: "payslip_id",
  payslip_history: "payslip_history_id",
  performance_review: "performance_review_id",
  pip: "pip_id",
  probation: "probation_id",
  promotion: "promotion_id",
  recommendation: "id",
  reference_check: "reference_check_id",
  reference_letter: "reference_letter_id",
  resignation: "resignation_id",
  resume: "resume_id",
  role: "role_id",
  role_permission: "id",
  salary_revision: "salary_revision_id",
  schedule_period_status: "schedule_period_status_id",
  showcause_warning_letter: "showcause_warning_letter_id",
  slot: "slot_id",
  survey_response: "id",
  survey_template: "id",
  suspension_letter: "suspension_letter_id",
  training: "training_id",
  transfer: "transfer_id",
  user_profile: "profile_id",
  users: "user_id",
  workflow_assignment: "id",
  workflow_assignment_step: "id",
  workflow_step: "id",
  workflow_template: "id",
};

/** The primary-key value of a returned row, stringified, or null. */
export function entityIdOf(
  model: string,
  row: Record<string, unknown> | null | undefined,
): string | null {
  if (!row) return null;

  const known = PRIMARY_KEYS[model];
  if (known && row[known] !== undefined && row[known] !== null) {
    return String(row[known]);
  }

  // Unknown or renamed model — fall back to the first id-shaped column.
  for (const [key, value] of Object.entries(row)) {
    if (value === null || value === undefined) continue;
    if (key === "id" || key.endsWith("_id")) return String(value);
  }
  return null;
}
