/**
 * Regenerate src/lib/audit/primary-keys.ts from prisma/schema.prisma.
 *
 * Prisma 7's runtime DMMF is trimmed — `Prisma.dmmf.datamodel.models[].fields`
 * carries only { name, kind, type }, with no `isId` — so the audit extension
 * has no way to discover primary keys at run time. This bakes them in instead.
 *
 * Run after adding or renaming a model:
 *   npx tsx scripts/gen-audit-primary-keys.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SCHEMA = resolve(process.cwd(), "prisma/schema.prisma");
const OUT = resolve(process.cwd(), "src/lib/audit/primary-keys.ts");

function parsePrimaryKeys(schema: string): Record<string, string> {
  const pks: Record<string, string> = {};
  const modelRe = /model\s+(\w+)\s*\{([\s\S]*?)\n\}/g;

  for (const match of schema.matchAll(modelRe)) {
    const [, name, body] = match;
    const lines = body
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l && !l.startsWith("//") && !l.startsWith("///") && !l.startsWith("@@"));

    const idLine = lines.find((l) => /\s@id\b/.test(l));
    if (idLine) pks[name] = idLine.split(/\s+/)[0];
  }
  return pks;
}

const pks = parsePrimaryKeys(readFileSync(SCHEMA, "utf8"));
const entries = Object.keys(pks)
  .sort()
  .map((model) => `  ${model}: "${pks[model]}",`)
  .join("\n");

const header = [
  "// ─────────────────────────────────────────────────────────────",
  "// Audit log — primary-key column for every model in prisma/schema.prisma.",
  "//",
  "// GENERATED by scripts/gen-audit-primary-keys.ts — re-run that after adding",
  "// or renaming a model. Prisma 7's runtime DMMF is trimmed (fields carry no",
  "// `isId`), so the audit extension cannot discover these at run time.",
  "//",
  "// A model missing from this map still audits correctly: entityIdOf() falls",
  "// back to the first id-shaped key on the row, which is the primary key for",
  "// every model in this schema (each declares its `@id` field first).",
  "// ─────────────────────────────────────────────────────────────",
  "",
].join("\n");

const body = `export const PRIMARY_KEYS: Record<string, string> = {
${entries}
};

/** The primary-key value of a returned row, stringified, or null. */
export function entityIdOf(
  model: string,
  row: Record<string, unknown> | null | undefined,
): string | null {
  if (!row) return null;

  const known = PRIMARY_KEYS[model];
  if (known && row[known] !== undefined && row[known] !== null) {
    return String(row[known]);
  }

  // Unknown or renamed model — fall back to the first id-shaped column.
  for (const [key, value] of Object.entries(row)) {
    if (value === null || value === undefined) continue;
    if (key === "id" || key.endsWith("_id")) return String(value);
  }
  return null;
}
`;

writeFileSync(OUT, `${header}\n${body}`);
console.log(`[gen-audit-primary-keys] wrote ${Object.keys(pks).length} models → ${OUT}`);
